rss: atom.xml
fancybox: true
favicon: favicon.png
inverse_sort: false  # Whether to sort all notes inversely
fold: false  # Whether to fold all the notebooks initially
scratch_name: 默认文件夹  # Notebook name of posts without categories variables
google_analytics:
